name: Publish

on:
  push:
    branches:
      - 'master'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    strategy:
      matrix:
        version: [16, 18]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}
      - name: Install dependencies
        run: npm ci
      - name: Create release
        id: create_release
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: npm run build
          commit: 'chore(release): update versioning and publish'
          title: 'chore(release): update versioning and publish'
